language: go
sudo: false
matrix:
  include:
    - go: 1.11.x
env:
  - GO111MODULE=on
before_install:
  - go get github.com/mitchellh/gox
script:
  - |-
    gox \
      -output="build/{{.Dir}}_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}" \
      -ldflags " \
        -X github.com/prometheus/common/version.Revision=${TRAVIS_COMMIT} \
        -X github.com/prometheus/common/version.Version=${TRAVIS_TAG} \
        -X github.com/prometheus/common/version.Branch=${TRAVIS_BRANCH} \
        -X github.com/prometheus/common/version.BuildDate=$(date +'%Y-%m-%d_%H:%M:%S') \
        -X github.com/prometheus/common/version.BuildUser=${USER} \
       "
before_deploy:
  - cd build
  - chmod +x ./*
  - for f in *; do tar -czf $f.tar.gz $f && rm $f; done
  - cd ..
deploy:
  provider: releases
  api_key:
    secure: T9WfMZhB+iGzABJU+Fo4DGhiDlBByiW2mQQs2RYtpCY2ooI65ejTkLquHDPGQRr2C7VoWNMiwzde1Nn2XplUSh4ayn0zBZ1nEUlbn6IyjkyX101e1rwwZspi/9731O9Nl4IJJuewy8I5BQvS52nJohM5qri2oUAQMBwHtFXzT1YbM8sIvYaDV0kLg9aodUFuH/dJxxptsYGNdvAHSnvXmW3j+pNIB/zxPOPUof/8kseDqpyUJtY8hzBKkDaxp8Q+nVsfmvYyQmWDFiFxXQ6Gzpe9I8saiqbb9c7QMoKwLzbc16VOdAmJ9SiVYwWXSTQ9aFNTJGwkTzBbvEvgKlDsir5PlWcZHxtmXNvgguAkQn2n2n8hATVmC5j2bYrmeILjJ5Qir3c06ZoBxNgqcxJU9RreO6Y7sdPVmfrgfOsJV5Dtn71kaEiUYAljyqNYuu+Ej0ZazBoWwiMpbswGSB3voy6u45qW2CMq+dbrlvVPI/8QYqb/Gax7l8lvoa4QAcg1ybYX7Q2f9edRVdoUwQJ/qpqt+4c9v8QH1QvZg4xKhgGXPsZK76wUxi6LYj3OOvX4TkzDMHB6DblzCC2Cdk9FrRqRZQyLDNOOPQxEBvL1tsGUIH4TceaxjT6qOxNAn048D2sQFxLLWTLbRjbbPlNP7xG9LoU83Yu5WaAmcDzs4EA=
  file_glob: true
  file: build/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: xxxcoltxxx/stream-telecom-balance-exporter
